# Generated by Django 4.2.14 on 2024-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temperature', models.DecimalField(decimal_places=1, max_digits=6)),
                ('min_temperature', models.DecimalField(decimal_places=1, max_digits=6)),
                ('precipitation', models.DecimalField(decimal_places=1, max_digits=6)),
                ('station_id', models.CharField(max_length=100)),
            ],
        ),
    ]
