# Generated by Django 4.2.14 on 2024-07-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('station_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('date', 'station_id')},
            },
        ),
        migrations.CreateModel(
            name='YearlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('station_id', models.IntegerField()),
                ('avg_max_temperature', models.FloatField(blank=True, null=True)),
                ('avg_min_temperature', models.FloatField(blank=True, null=True)),
                ('total_precipitation_cm', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
