# Generated by Django 4.2.14 on 2024-07-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherrecord_yearlystats_delete_weatherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecord',
            name='station_id',
            field=models.CharField(),
        ),
    ]
