# Generated by Django 4.2.14 on 2024-07-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weatherrecord_station_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlystats',
            options={'managed': False},
        ),
    ]
